=== tomas-izv/LMSGI/xml/Ejercicio2/Ejercicio2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="CatalogoPeliculas">

        <xs:complexType>

            <xs:sequence>
                <xs:element name="Pelicula" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>

                            <xs:element name="Titulo" type="xs:string" />

                            <xs:element name="Duracion" type="xs:integer" />

                            <xs:element name="Genero">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="Drama" />
                                        <xs:enumeration value="Comedia" />
                                        <xs:enumeration value="Terror" />
                                        <xs:enumeration value="Thriller" />
                                        <xs:enumeration value="Sci-Fi and Fantasy" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>

                            <xs:element name="Actores">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Actor" type="xs:string" maxOccurs="3" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>

                            <xs:element name="Fecha">
                                    <xs:simpleType>
                                        <xs:restriction base="xs:integer">
                                            <xs:minExclusive value="1900"></xs:minExclusive>
                                        </xs:restriction>
                                    </xs:simpleType>
                            </xs:element>


                            <xs:element name="Director" type="xs:string" />

                            <xs:element name="Formato" default="DVD">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="DVD" />
                                        <xs:enumeration value="VHS" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

            </xs:sequence>

        </xs:complexType>

    </xs:element>

</xs:schema>

=== tomas-izv/LMSGI/xml/Ejercicio2/Ejercicio2.xml
<?xml version="1.0"?>
<CatalogoPeliculas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="Ejercicio2.xsd">
    <Pelicula>
        <Titulo>The Matrix</Titulo>
        <Duracion>136</Duracion>
        <Genero>Sci-Fi and Fantasy</Genero>
        <Actores>
            <Actor>Keanu Reeves</Actor>
            <Actor>Laurence Fishburne</Actor>
            <Actor>Carrie Ann Moss</Actor>
        </Actores>
        <Fecha>1999</Fecha>
        <Director>Wachowski Brothers</Director>
        <Formato>DVD</Formato>
    </Pelicula>

    <Pelicula>
        <Titulo>Titanic</Titulo>
        <Duracion>194</Duracion>
        <Genero>Drama</Genero>
        <Actores>
            <Actor>Leonardo DiCaprio</Actor>
            <Actor>Kate Winslet</Actor>
        </Actores>
        <Fecha>1999</Fecha>
        <Director>James Cameron</Director>
        <Formato>DVD</Formato>
    </Pelicula>
    
    <Pelicula>
        <Titulo>The Sixth Sense</Titulo>
        <Duracion>106</Duracion>
        <Genero>Thriller</Genero>
        <Actores>
            <Actor>Bruce Willis</Actor>
            <Actor>Haley Joel Osment</Actor>
        </Actores>
        <Fecha>1999</Fecha>
        <Director>M. Night Shyamalan</Director>
        <Formato>VHS</Formato>
    </Pelicula>
</CatalogoPeliculas>
